#!/bin/sh
# Copyright 2003-2009, Mike Solomon <mas63@cornell.edu>
# SIMBL is released under the GNU General Public License v2.
# http://www.opensource.org/licenses/gpl-2.0.php

PACKAGE_PATH=$1
INSTALL_PATH=$2
INSTALL_VOLUME=$3
SYSTEM_ROOT=$4

RESOURCES="${PACKAGE_PATH}/Contents/Resources"

# FIXME(mike) maybe we should copy this out of the install package instead?
LAUNCHD_PLIST="/Library/ScriptingAdditions/SIMBL.osax/Contents/Resources/SIMBL Agent.app/Contents/Resources/net.culater.SIMBL.Agent.plist"

# remove old InputManager if it exists, otherwise these
# two will contend when applications run under 32-bit mode
SIMBL_INPUTMANAGER="/Library/InputManagers/SIMBL"
if [ -d "$SIMBL_INPUTMANAGER" ]; then
  rm -rf "$SIMBL_INPUTMANAGER"
fi

LAUNCH_AGENTS_DIR="/Library/LaunchAgents"
if [ ! -d "$LAUNCH_AGENTS_DIR" ]; then
  mkdir -p "$LAUNCH_AGENTS_DIR"
fi

# ensure that this loads on restart
cp "$LAUNCHD_PLIST" "$LAUNCH_AGENTS_DIR"

# create a system-wide location for plugins
SIMBL_PLUGINS_DIR="/Library/Application Support/SIMBL/Plugins"
if [ ! -d "$SIMBL_PLUGINS_DIR" ]; then
  mkdir -p "$SIMBL_PLUGINS_DIR"
  chown root:admin "$SIMBL_PLUGINS_DIR"
  chmod 775 "$SIMBL_PLUGINS_DIR"
fi

# ensure that ScriptingAdditions is world-readable
SCRIPTING_ADDITIONS_DIR="/Library/ScriptingAdditions"
if [ ! -d "$SCRIPTING_ADDITIONS_DIR" ]; then
  chown root:admin "$SCRIPTING_ADDITIONS_DIR"
  chmod 775 "$SCRIPTING_ADDITIONS_DIR"
fi

# stop any running agent by unloading it, in case we have made changes
# to the agent that won't take effect until the application is restarted
echo "Stop SIMBL Agent"
echo /bin/launchctl unload -F -S Aqua "${LAUNCHD_PLIST}"
/bin/launchctl unload -F -S Aqua "${LAUNCHD_PLIST}"

echo "Start SIMBL Agent"
echo /bin/launchctl load -F -S Aqua "${LAUNCHD_PLIST}"
/bin/launchctl load -F -S Aqua "${LAUNCHD_PLIST}"
